### ISSUE TITLE
FontAwesome issue

### ISSUE THREAD

**Issue by sb15** [snowair/phalcon-debugbar#34]
Hi.

Cool plugin!

Find issue when font-awesome style is not loaded on site then icons is missing.

In file Resources/font-awesome/style.css
Looks like font-family must be PhpDebugbarFontAwesome instead FontAwesome

With this fix icons is visible.

**Comment by icaroscherma** [comment]
Actually the problem is generated because Phalcon's Debugbar do a `prepend` with `phpdebugbar-` before every css class in your View.

Said that, your generated HTML is:
`<i class="phpdebugbar-fa phpdebugbar-fa-clock-o"></i>`

And what the FA's CSS expects is: 
`<i class="fa fa-clock-o"></i>`

You can test in your browser by changing the class by `Inspect element`...
